version: '3'

vars:
  VERSION:
    sh: git describe --tags 2>/dev/null || echo "dev"
  BUILD_COMMIT:
    sh: git rev-parse HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date "+%F %T"
  LDFLAGS: >-
    -w -s
    -X 'main.version={{.VERSION}}'
    -X 'main.buildDate={{.BUILD_DATE}}'
    -X 'main.commit={{.BUILD_COMMIT}}'

tasks:
  default:
    desc: Build for current platform
    cmds:
      - task: build

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist coverage.out coverage.html

  fmt:
    desc: Format code
    cmds:
      - gofmt -w -s .

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run unit tests
    cmds:
      - go test -v -race ./...

  test-integration:
    desc: Run integration tests (requires Docker)
    cmds:
      - go test -v -race -tags=integration ./... -timeout 180s

  test-cover:
    desc: Run tests with coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  build:
    desc: Build for current platform
    cmds:
      - go build -trimpath -o dist/dnsctl -ldflags "{{.LDFLAGS}}"

  install:
    desc: Install to GOPATH/bin
    cmds:
      - go install -trimpath -ldflags "{{.LDFLAGS}}"

  # Internal cross-compilation task
  build-cross:
    label: build-{{.TASK}}
    internal: true
    cmds:
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOAMD64={{.GOAMD64}} \
        go build -trimpath -o dist/dnsctl-{{.TASK}} -ldflags "{{.LDFLAGS}}"

  # Cross-compilation targets
  linux-386:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: 386 }

  linux-amd64:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: amd64 }

  linux-amd64-v3:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: amd64, GOAMD64: v3 }

  linux-armv5:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: arm, GOARM: 5 }

  linux-armv6:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: arm, GOARM: 6 }

  linux-armv7:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: arm, GOARM: 7 }

  linux-arm64:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: linux, GOARCH: arm64 }

  darwin-amd64:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: darwin, GOARCH: amd64 }

  darwin-arm64:
    cmds:
      - task: build-cross
        vars: { TASK: "{{.TASK}}", GOOS: darwin, GOARCH: arm64 }

  checksums:
    desc: Generate checksums.txt for release
    cmds:
      - cd dist && shasum -a 256 dnsctl-* > checksums.txt
      - cat dist/checksums.txt

  release:
    desc: Build all release binaries
    cmds:
      - task: clean
      - task: test
      - task: linux-386
      - task: linux-amd64
      - task: linux-amd64-v3
      - task: linux-armv5
      - task: linux-armv6
      - task: linux-armv7
      - task: linux-arm64
      - task: darwin-amd64
      - task: darwin-arm64
      - task: checksums

  gh-release:
    desc: Create GitHub release with binaries
    deps: [release]
    cmds:
      - gh release create {{.VERSION}} -t "Release {{.VERSION}}" ./dist/*
